export const ADD_TODO_THUNK = 'ADD_TODO_THUNK';
export const DELETE_TODO_THUNK = 'DELETE_TODO_THUNK';
export const TODO_COMPLETED_THUNK = 'TODO_COMPLETED_THUNK';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_THUNK = 'ADD_USER_THUNK';
